<?php
/**
 * Description of curlConstants
 *
 * @author almaz
 */
class curlConstants {
    public
        $curlConstants = array (CURLOPT_IPRESOLVE => 'CURLOPT_IPRESOLVE');
    public $opts = array (
CURLOPT_IPRESOLVE => 'CURLOPT_IPRESOLVE',
CURLOPT_DNS_USE_GLOBAL_CACHE => 'CURLOPT_DNS_USE_GLOBAL_CACHE',
CURLOPT_DNS_CACHE_TIMEOUT => 'CURLOPT_DNS_CACHE_TIMEOUT',
CURLOPT_PORT => 'CURLOPT_PORT',
CURLOPT_FILE => 'CURLOPT_FILE',
CURLOPT_READDATA => 'CURLOPT_READDATA',
CURLOPT_INFILE => 'CURLOPT_INFILE',
CURLOPT_INFILESIZE => 'CURLOPT_INFILESIZE',
CURLOPT_URL => 'CURLOPT_URL',
CURLOPT_PROXY => 'CURLOPT_PROXY',
CURLOPT_VERBOSE => 'CURLOPT_VERBOSE',
CURLOPT_HEADER => 'CURLOPT_HEADER',
CURLOPT_HTTPHEADER => 'CURLOPT_HTTPHEADER',
CURLOPT_NOPROGRESS => 'CURLOPT_NOPROGRESS',
/**
 * Available since PHP 5.3.0
 * @link http://php.net/manual/en/curl.constants.php
 */
CURLOPT_PROGRESSFUNCTION => 'CURLOPT_PROGRESSFUNCTION',
CURLOPT_NOBODY => 'CURLOPT_NOBODY',
CURLOPT_FAILONERROR => 'CURLOPT_FAILONERROR',
CURLOPT_UPLOAD => 'CURLOPT_UPLOAD',
CURLOPT_POST => 'CURLOPT_POST',
CURLOPT_FTPLISTONLY => 'CURLOPT_FTPLISTONLY',
CURLOPT_FTPAPPEND => 'CURLOPT_FTPAPPEND',
CURLOPT_NETRC => 'CURLOPT_NETRC',
/**
 * This constant is not available when open_basedir
 * or safe_mode are enabled.
 * @link http://php.net/manual/en/curl.constants.php
 */
CURLOPT_FOLLOWLOCATION => 'CURLOPT_FOLLOWLOCATION',
CURLOPT_PUT => 'CURLOPT_PUT',
CURLOPT_USERPWD => 'CURLOPT_USERPWD',
CURLOPT_PROXYUSERPWD => 'CURLOPT_PROXYUSERPWD',
CURLOPT_RANGE => 'CURLOPT_RANGE',
CURLOPT_TIMEOUT => 'CURLOPT_TIMEOUT',
CURLOPT_TIMEOUT_MS => 'CURLOPT_TIMEOUT_MS',
CURLOPT_POSTFIELDS => 'CURLOPT_POSTFIELDS',
CURLOPT_REFERER => 'CURLOPT_REFERER',
CURLOPT_USERAGENT => 'CURLOPT_USERAGENT',
CURLOPT_FTPPORT => 'CURLOPT_FTPPORT',
CURLOPT_FTP_USE_EPSV => 'CURLOPT_FTP_USE_EPSV',
CURLOPT_LOW_SPEED_LIMIT => 'CURLOPT_LOW_SPEED_LIMIT',
CURLOPT_LOW_SPEED_TIME => 'CURLOPT_LOW_SPEED_TIME',
CURLOPT_RESUME_FROM => 'CURLOPT_RESUME_FROM',
CURLOPT_COOKIE => 'CURLOPT_COOKIE',
/**
 * Available since PHP 5.1.0
 * @link http://php.net/manual/en/curl.constants.php
 */
CURLOPT_COOKIESESSION => 'CURLOPT_COOKIESESSION',
/**
 * Available since PHP 5.1.0
 * @link http://php.net/manual/en/curl.constants.php
 */
CURLOPT_AUTOREFERER => 'CURLOPT_AUTOREFERER',
CURLOPT_SSLCERT => 'CURLOPT_SSLCERT',
CURLOPT_SSLCERTPASSWD => 'CURLOPT_SSLCERTPASSWD',
CURLOPT_WRITEHEADER => 'CURLOPT_WRITEHEADER',
CURLOPT_SSL_VERIFYHOST => 81,
CURLOPT_COOKIEFILE => 10031,
CURLOPT_SSLVERSION => 32,
CURLOPT_TIMECONDITION => 33,
CURLOPT_TIMEVALUE => 34,
CURLOPT_CUSTOMREQUEST => 10036,
CURLOPT_STDERR => 10037,
CURLOPT_TRANSFERTEXT => 53,
CURLOPT_RETURNTRANSFER => 19913,
CURLOPT_QUOTE => 10028,
CURLOPT_POSTQUOTE => 10039,
CURLOPT_INTERFACE => 10062,
CURLOPT_KRB4LEVEL => 10063,
CURLOPT_HTTPPROXYTUNNEL => 61,
CURLOPT_FILETIME => 69,
CURLOPT_WRITEFUNCTION => 20011,
CURLOPT_READFUNCTION => 20012,
CURLOPT_HEADERFUNCTION => 20079,
CURLOPT_MAXREDIRS => 68,
CURLOPT_MAXCONNECTS => 71,
CURLOPT_CLOSEPOLICY => 72,
CURLOPT_FRESH_CONNECT => 74,
CURLOPT_FORBID_REUSE => 75,
CURLOPT_RANDOM_FILE => 10076,
CURLOPT_EGDSOCKET => 10077,
CURLOPT_CONNECTTIMEOUT => 78,
CURLOPT_CONNECTTIMEOUT_MS => 156,
CURLOPT_SSL_VERIFYPEER => 64,
CURLOPT_CAINFO => 10065,
CURLOPT_CAPATH => 10097,
CURLOPT_COOKIEJAR => 10082,
CURLOPT_SSL_CIPHER_LIST => 10083,
CURLOPT_BINARYTRANSFER => 19914,
CURLOPT_NOSIGNAL => 99,
CURLOPT_PROXYTYPE => 101,
CURLOPT_BUFFERSIZE => 98,
CURLOPT_HTTPGET => 80,
CURLOPT_HTTP_VERSION => 84,
CURLOPT_SSLKEY => 10087,
CURLOPT_SSLKEYTYPE => 10088,
CURLOPT_SSLKEYPASSWD => 10026,
CURLOPT_SSLENGINE => 10089,
CURLOPT_SSLENGINE_DEFAULT => 90,
CURLOPT_SSLCERTTYPE => 10086,
CURLOPT_CRLF => 27,
CURLOPT_ENCODING => 10102,
CURLOPT_PROXYPORT => 59,
CURLOPT_UNRESTRICTED_AUTH => 105,
CURLOPT_FTP_USE_EPRT => 106,
/**
 * Available since PHP 5.2.1
 * @link http://php.net/manual/en/curl.constants.php
 */
CURLOPT_TCP_NODELAY => 121,
CURLOPT_HTTP200ALIASES => 10104,
CURLOPT_HTTPAUTH => 107,
CURLOPT_PROXYAUTH => 111,
CURLOPT_FTP_CREATE_MISSING_DIRS => 110,
/**
 * Available since PHP 5.2.4
 * @link http://php.net/manual/en/curl.constants.php
 */
CURLOPT_PRIVATE => 10103,

/**
 * Available since PHP 5.1.0
 * @link http://php.net/manual/en/curl.constants.php
 */
CURLOPT_FTPSSLAUTH => 129,

/**
 * Available since PHP 5.2.0
 * @link http://php.net/manual/en/curl.constants.php
 */
CURLOPT_FTP_SSL => 119,
/**
 * Available since PHP 5.2.0
 * @link http://php.net/manual/en/curl.constants.php
 */
CURLOPT_FTP_FILEMETHOD => 138,
CURLOPT_FTP_SKIP_PASV_IP => 137,

);

}